name: foodie_loc
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:

  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8

  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7
  google_sign_in: ^5.4.4
  fluttertoast: ^8.2.12
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  http: ^1.4.0
  permission_handler: ^12.0.0+1
  mime: ^2.0.0
  http_parser: ^4.1.2
  shared_preferences: ^2.5.3
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/loginpage.jpg
    - assets/register.jpg
    - assets/google.png
    - assets/msq1.png
    - assets/msq2.png
    - assets/msq3.png
    - assets/msq4.png
    - assets/restaurant/jaishree.webp
    - assets/restaurant/prime.webp
    - assets/restaurant/rk.webp
    - assets/logout.png
    - assets/cities.json
    - assets/dishes.json
    - assets/icon/app_icon.png
    - assets/back.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: true



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
